CREATE TABLE Recetas (
    RecId TINYINT PRIMARY KEY IDENTITY(1,1),
	NomRec NVARCHAR (40) NOT NULL,
	ElRec NVARCHAR (600) NOT NULL,
	TRec NVARCHAR (15) NOT NULL,
	DifId TINYINT FOREIGN KEY REFERENCES Dificultades NOT NULL,
	CatId TINYINT FOREIGN KEY REFERENCES Categorias NOT NULL
);